export const LEGAL_CONTACT_EMAIL = "enrique.catalan.hoeflich@gmail.com";
export const LEGAL_EFFECTIVE_DATE = "September 26, 2026";
export const LEGAL_ENTITY_NOTE =
  "YourTruths is a Mexican-owned company project that operates an AI evaluation platform for users internationally, with a primary focus on customers in the United States.";

export type LegalSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type LegalDoc = {
  title: string;
  slug: string;
  intro: string;
  sections: LegalSection[];
};

export const FOOTER_LINKS = [
  { href: "/terms", label: "Terms of Service" },
  { href: "/privacy", label: "Privacy Policy" },
  { href: "/refunds", label: "Refund & Cancellation Policy" },
  { href: "/ai-disclaimer", label: "AI Disclaimer" },
  { href: "/content-policy", label: "User Content & Copyright Policy" },
  { href: "/contact", label: "Contact" },
] as const;

export const TERMS_OF_SERVICE: LegalDoc = {
  title: "Terms of Service",
  slug: "terms",
  intro:
    "These Terms of Service (“Terms”) govern your access to and use of YourTruths, including our website, applications, and related services (collectively, the “Service”). By accessing or using the Service, you agree to these Terms. If you do not agree, do not use the Service.",
  sections: [
    {
      heading: "1. About YourTruths",
      paragraphs: [
        LEGAL_ENTITY_NOTE,
        "YourTruths is an AI evaluation engine that produces independent, structured opinions on creative work, ideas, and related submissions. Free AI evaluations cover text (including writing such as poetry and screenplays). Music, video, and images use a Hybrid path: a real person experiences the work, and YourTruths AI (Pro Examiner) rewrites those notes into a clear structured evaluation with a 0–100 YourTruths score, strengths, weaknesses, and a focused verdict.",
        "The Service provides evaluations and opinions. It does not guarantee business, artistic, financial, professional, legal, medical, academic, or other outcomes.",
      ],
    },
    {
      heading: "2. Eligibility",
      paragraphs: [
        "You must be legally able to enter into a binding agreement to use the Service. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.",
        "You are responsible for complying with the laws that apply to you in your jurisdiction when using the Service, including when you access YourTruths from the United States or elsewhere.",
      ],
    },
    {
      heading: "3. Accounts and authentication",
      paragraphs: [
        "Certain features of the Service may require you to create an account or sign in (including through a third-party provider such as Google). When you create an account, you are responsible for maintaining the confidentiality of your credentials and for activity under your account.",
        "You agree to provide accurate information and to notify us promptly of any unauthorized use of your account.",
      ],
    },
    {
      heading: "4. Free and paid services",
      paragraphs: [
        "Free tier: YourTruths offers free AI opinions on text — for example social posts, marketing plans, job descriptions, and written artwork such as poetry or screenplays — subject to usage limits described on the Service (for example, a daily number of free AI opinions). Free evaluations are generated by YourTruths AI and do not include a human reviewer. Images, video, and music are not included in the free AI path.",
        "Paid Hybrid: Music, video, images, and other file reviews may require a human experiencing the work plus AI structuring of the reviewer’s notes. Paid packages and credit amounts are described on the Pricing page (for example, Hybrid and Hybrid PRO). Features, limits, and prices may change; the Pricing page and purchase flow control what is offered at the time of purchase.",
      ],
    },
    {
      heading: "5. Credits, purchases, and subscriptions",
      paragraphs: [
        "Paid features may require purchase of credits or packages. Purchases are subject to these Terms and our Refund & Cancellation Policy.",
        "Credits are for use of the Service as described at purchase and on the Pricing page (including per-minute billing in time blocks for music and video, and a standard credit amount for images and long documents). Credits are not transferable unless we expressly allow it. Unused credits do not create an ownership interest in YourTruths.",
        "Payments are processed by third-party payment processors. Their terms may also apply to the payment transaction. YourTruths does not store full payment card numbers on its own systems when a processor handles checkout.",
      ],
    },
    {
      heading: "6. Hybrid reviews",
      paragraphs: [
        "For eligible music and video submissions, a human reviewer listens to or watches your work and provides notes or immediate reactions. YourTruths AI then rewrites those notes into a structured evaluation (including score and verdict format used by the Service).",
        "Human reviewers provide individual perspectives. Their views are not a universal consensus, professional certification, market forecast, or guarantee of audience response.",
        "Review timing varies with queue volume and reviewer availability. Any estimated wait times shown in the Service are approximate and not guarantees. Longer video may require a higher-tier package where the Service states a duration limit.",
      ],
    },
    {
      heading: "7. User responsibilities",
      paragraphs: [
        "You are responsible for the content you submit, the decisions you make based on evaluations, and your compliance with these Terms and applicable law.",
        "You must have the rights necessary to upload and request evaluation of any material you submit, including rights in music, video, images, text, and other works.",
      ],
    },
    {
      heading: "8. Prohibited content and conduct",
      paragraphs: [
        "You may not use the Service to submit or promote content that is unlawful, infringing, harmful, abusive, exploitative of minors, or that violates the rights of others. You may not disrupt the Service, attempt to bypass usage limits or payment requirements, or misuse review workflows.",
        "We may refuse, remove, or limit submissions or access when we reasonably believe these Terms or the law have been violated.",
      ],
      bullets: [
        "Illegal content or content that facilitates crime",
        "Copyrighted material uploaded without authorization",
        "Malware, phishing, or deceptive technical content",
        "Harassment, hate content intended to threaten or abuse, or sexual content involving minors",
        "Attempts to scrape, overload, or interfere with the Service",
      ],
    },
    {
      heading: "9. Intellectual property",
      paragraphs: [
        "YourTruths and its branding, software, interface, prompts, ranking system, evaluation frameworks, and related materials are owned by YourTruths or its licensors and are protected by intellectual property laws.",
        "These Terms do not transfer ownership of YourTruths intellectual property to you. You may use the Service as offered; you may not copy, resell, or exploit the platform itself except as expressly permitted.",
      ],
    },
    {
      heading: "10. User-uploaded content",
      paragraphs: [
        "You retain ownership of the content you upload. You grant YourTruths a limited license to host, process, transmit, display, and otherwise use that content solely as needed to provide the evaluation or review you request (including AI processing and, where applicable, human review).",
        "Additional details appear in our User Content & Copyright Policy and Privacy Policy.",
      ],
    },
    {
      heading: "11. Third-party AI and service providers",
      paragraphs: [
        "The Service relies on third-party providers as needed for AI inference (large language model APIs), hosting, authentication, email, and payments. Your content and account data may be processed by those providers to operate the Service, subject to their terms and our Privacy Policy.",
        "We do not control third-party services and are not responsible for their outages, errors, or policy changes beyond what applicable law requires.",
      ],
    },
    {
      heading: "12. Service availability",
      paragraphs: [
        "We aim to keep the Service available but do not guarantee uninterrupted, error-free, or always-available operation. Features may be added, changed, suspended, or discontinued.",
        "AI capacity, human reviewer availability, and usage limits may constrain use of the Service at any time.",
      ],
    },
    {
      heading: "13. Disclaimer of guarantees",
      paragraphs: [
        "THE SERVICE AND ALL EVALUATIONS, SCORES, VERDICTS, AND RELATED OUTPUTS ARE PROVIDED “AS IS” AND “AS AVAILABLE.” TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOURTRUTHS DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.",
        "YourTruths does not guarantee that any evaluation is accurate, complete, unbiased, or suitable for any particular purpose, or that following an evaluation will produce any result.",
      ],
    },
    {
      heading: "14. Limitation of liability",
      paragraphs: [
        "TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOURTRUTHS AND ITS OPERATORS, CONTRIBUTORS, AND SUPPLIERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, LOST REVENUE, LOST DATA, OR BUSINESS INTERRUPTION, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE OR RELIANCE ON ANY EVALUATION.",
        "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID TO YOURTRUTHS FOR THE SERVICE IN THE THREE MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY, OR (B) USD $50 IF YOU HAVE NOT PAID ANY AMOUNTS.",
        "Some jurisdictions do not allow certain limitations; in those cases, our liability is limited to the fullest extent permitted by law. Mandatory consumer protections in your place of residence remain available where they cannot be waived.",
      ],
    },
    {
      heading: "15. Termination",
      paragraphs: [
        "You may stop using the Service at any time. We may suspend or terminate access if you violate these Terms, if required by law, or if we discontinue the Service.",
        "Sections that by their nature should survive termination (including intellectual property, disclaimers, limitations of liability, and governing law) will survive.",
      ],
    },
    {
      heading: "16. Governing law and jurisdiction",
      paragraphs: [
        "These Terms are governed by the laws of the United Mexican States (Mexico), without regard to conflict-of-law principles, except where mandatory consumer protections in your country of residence (including the United States) cannot be waived.",
        "Subject to applicable mandatory law, courts located in Mexico shall have jurisdiction over disputes arising out of or relating to these Terms or the Service. If you are a consumer in a jurisdiction that requires local courts or protections, those mandatory rights remain available to you.",
      ],
    },
    {
      heading: "17. Changes to the Terms",
      paragraphs: [
        "We may update these Terms from time to time. The “Effective date” at the top of the page will be revised when changes are posted. Continued use of the Service after changes become effective constitutes acceptance of the updated Terms, except where applicable law requires additional consent.",
      ],
    },
    {
      heading: "18. Contact",
      paragraphs: [
        `Questions about these Terms: ${LEGAL_CONTACT_EMAIL}. You may also use the Contact page on the Service.`,
      ],
    },
  ],
};

export const PRIVACY_POLICY: LegalDoc = {
  title: "Privacy Policy",
  slug: "privacy",
  intro:
    "This Privacy Policy explains how YourTruths collects, uses, stores, and shares information when you use the Service. It is written for users internationally, including customers in the United States and users in Mexico.",
  sections: [
    {
      heading: "1. Who we are",
      paragraphs: [
        LEGAL_ENTITY_NOTE,
        `Privacy requests: ${LEGAL_CONTACT_EMAIL}.`,
      ],
    },
    {
      heading: "2. Information we collect",
      paragraphs: [
        "Depending on how you use the Service, we may collect the following categories of information.",
      ],
      bullets: [
        "Account information: name, email address, and identifiers provided by your sign-in provider (for example, Google) when you create or use an account.",
        "Submitted content: text, PDFs, images, descriptions, music, video files, and related notes you upload or paste for evaluation.",
        "Evaluation outputs: YourTruths scores, verdicts, strengths and weaknesses, human review notes, and related result metadata.",
        "Payment and credit information: purchase status, pack type, credit balance metadata, and transaction identifiers. Full payment card details are handled by our payment processor, not stored by YourTruths as complete card numbers.",
        "Usage and technical information: IP address, device or browser type, pages viewed, timestamps, error logs, and similar diagnostics needed to operate and secure the Service.",
        "Communications: messages you send us for support, privacy, refund, or legal requests.",
      ],
    },
    {
      heading: "3. Uploaded files and content",
      paragraphs: [
        "When you submit content, it is processed to generate an AI evaluation or to queue a Hybrid review.",
        "For music and video Hybrid workflows, uploaded media files are intended to be temporary: after the evaluation result is saved, the media file is deleted from primary application storage. The score, structured opinion, and related metadata may be retained so you can view results and history and so we can operate the Service.",
        "Free AI evaluations (text, PDFs, images, physical appearance, and similar) and their results may be stored so the Service can display outcomes and history.",
        "We do not claim that content is never stored, never transmitted to providers, or instantly erased from every backup or log. Retention follows the operational design of the Service and our providers’ systems.",
      ],
    },
    {
      heading: "4. How we use information",
      paragraphs: [
        "We use information to provide, maintain, secure, and improve the Service; to generate AI evaluations through Pro Examiner and related systems; to facilitate human review for music and video; to manage accounts, credits, and purchases; to enforce usage limits; to communicate with you; to prevent abuse; and to comply with law.",
      ],
    },
    {
      heading: "5. AI processing",
      paragraphs: [
        "Submitted content and related prompts may be sent to third-party AI providers (large language model APIs) to generate free AI opinions or to rewrite human reviewer notes into structured evaluations. Those providers process data according to their own terms and privacy policies.",
        "AI outputs can be inaccurate or incomplete. See our AI Disclaimer.",
      ],
    },
    {
      heading: "6. Human review processing",
      paragraphs: [
        "For music and video Hybrid reviews, authorized reviewers access the submitted media and context needed to form an opinion. Access is for performing the review, not for unrelated personal use.",
        "Human notes may be stored with the job and used by YourTruths AI to produce the final structured evaluation.",
      ],
    },
    {
      heading: "7. Model training",
      paragraphs: [
        "YourTruths does not operate a program that uses your uploads to train a proprietary YourTruths foundation model.",
        "Content processed by third-party AI or infrastructure providers may be handled under those providers’ policies, which can differ from ours. We do not claim that no provider ever logs or retains data under its own rules. Contact us if you need clarification about our configuration.",
      ],
    },
    {
      heading: "8. File retention and deletion",
      paragraphs: [
        "Music and video uploads for Hybrid review are intended to be removed after the opinion is finalized. Evaluation results, scores, and related records may remain available in history or server storage.",
        "Backups, logs, and provider-side retention may persist for a limited period after deletion from primary application storage. We do not promise irreversible immediate deletion from every system in every case.",
      ],
    },
    {
      heading: "9. Third-party service providers",
      paragraphs: [
        "We use providers for hosting, AI inference, authentication, payments, email delivery, security, and related operations. These providers process data as needed to perform services for us, subject to their agreements and policies.",
      ],
    },
    {
      heading: "10. Data security",
      paragraphs: [
        "We take reasonable administrative and technical measures appropriate to the nature of the Service. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
      ],
    },
    {
      heading: "11. International users and transfers",
      paragraphs: [
        "YourTruths is Mexican-owned and serves users internationally, including customers in the United States. Information may be processed in Mexico, the United States, or other countries where we or our providers operate.",
        "Where required, we rely on appropriate transfer mechanisms and contractual protections available under applicable law.",
      ],
    },
    {
      heading: "12. Privacy rights",
      paragraphs: [
        "Depending on where you live, you may have rights to access, correct, delete, or restrict certain personal data, or to object to certain processing, subject to legal exceptions.",
      ],
    },
    {
      heading: "13. Mexican ARCO rights",
      paragraphs: [
        "If you are in Mexico, you may have ARCO rights (Access, Rectification, Cancellation, and Opposition) under applicable Mexican data-protection law, as well as related rights regarding consent and processing.",
        `To exercise ARCO or related Mexican privacy rights, contact ${LEGAL_CONTACT_EMAIL} with enough detail to verify your request. We will respond in accordance with applicable law.`,
      ],
    },
    {
      heading: "14. California and U.S. privacy rights",
      paragraphs: [
        "If you are a U.S. resident, including in California, you may have rights under applicable state privacy laws, such as rights to know or access, delete, correct, or opt out of certain data practices, subject to eligibility and exceptions.",
        "YourTruths is not designed to sell personal information. If that practice ever changes, we will update this Policy and provide required opt-out mechanisms.",
        `To make a U.S. privacy request, email ${LEGAL_CONTACT_EMAIL}. We may need to verify your identity before fulfilling the request.`,
      ],
    },
    {
      heading: "15. Children",
      paragraphs: [
        "The Service is not directed to children under 13 (or the higher age required in your jurisdiction). Do not use the Service if you are under the applicable age. Contact us if you believe we have collected personal information from a child.",
      ],
    },
    {
      heading: "16. Changes to this Policy",
      paragraphs: [
        "We may update this Privacy Policy from time to time. The effective date will be updated when changes are posted.",
      ],
    },
    {
      heading: "17. Contact / privacy requests",
      paragraphs: [
        `Email: ${LEGAL_CONTACT_EMAIL}. You may also use the Contact page.`,
      ],
    },
  ],
};

export const REFUND_POLICY: LegalDoc = {
  title: "Refund & Cancellation Policy",
  slug: "refunds",
  intro:
    "This Refund & Cancellation Policy explains how free usage and paid YourTruths purchases are handled. Refunds, where available, are processed through our support process and payment providers—not as an automatic in-product guarantee for every purchase.",
  sections: [
    {
      heading: "1. Free AI usage",
      paragraphs: [
        "Free AI opinions on supported text categories (subject to daily or other usage limits) are provided at no charge. Free usage is not a paid purchase and is not refundable.",
      ],
    },
    {
      heading: "2. Hybrid credits",
      paragraphs: [
        "Hybrid packages provide credits for human review of music, video, images, long PDFs, and other supported files, as described on the Pricing page. A real person experiences the work; YourTruths AI structures the reviewer’s notes into the final opinion.",
        "Credit amounts are billed as described at purchase and on Pricing: music and video use credits per minute in 5-minute blocks; images and long documents use a standard credit amount. Once credits are consumed to submit a Hybrid job, those credits are generally considered used—even if you later disagree with the opinion—because reviewer time and processing have been allocated.",
      ],
    },
    {
      heading: "3. Pro credits",
      paragraphs: [
        "Hybrid PRO and similar higher-tier packages may include more credits, priority handling, longer media support, or private-use features as described at purchase.",
        "The same rule applies: unused credits may be reviewed under the conditions below; consumed credits are ordinarily non-refundable.",
      ],
    },
    {
      heading: "4. When purchases become non-refundable",
      paragraphs: [
        "Unless required by applicable law or expressly agreed by us in writing:",
      ],
      bullets: [
        "Purchases are non-refundable after credits have been used.",
        "Unused purchases may become non-refundable after any refund window stated at purchase or in your confirmation.",
        "Dissatisfaction with an opinion, score, artistic disagreement, or creative preference is not by itself grounds for a refund.",
      ],
    },
    {
      heading: "5. Failed or duplicate payments",
      paragraphs: [
        "If a payment fails, you generally should not be charged. If you are charged in error or charged twice for the same purchase, contact us promptly with the transaction details so we can investigate with our payment provider.",
        "Resolution depends on payment-provider records and applicable card-network or banking processes.",
      ],
    },
    {
      heading: "6. Service issues",
      paragraphs: [
        "If a paid Hybrid job cannot be completed due to a clear failure on our side (for example, a paid submission permanently cannot be reviewed because of an internal fault), contact us. We may, at our discretion, restore the credits billed for that job, provide a replacement review, or issue a refund where our payment systems support it.",
        "We do not promise refunds for third-party AI outages, your device or network issues, or content we refuse because it violates our Terms or Content Policy.",
      ],
    },
    {
      heading: "7. Cancellations",
      paragraphs: [
        "YourTruths primarily offers one-time credit packs rather than automatically renewing subscriptions. If a subscription product is offered, cancellation terms will be described at signup and in an updated version of this Policy.",
        "Stopping use of the Service does not automatically refund unused credits unless we approve a refund request.",
      ],
    },
    {
      heading: "8. How to request a refund",
      paragraphs: [
        `Email ${LEGAL_CONTACT_EMAIL} with your account email, purchase date, approximate amount, pack type, and a short description of the issue.`,
        "We will review eligible requests in good faith. Response times may vary. Except where mandatory law requires otherwise, this Policy does not create an automatic right to a refund for every purchase.",
      ],
    },
  ],
};

export const AI_DISCLAIMER: LegalDoc = {
  title: "AI Disclaimer",
  slug: "ai-disclaimer",
  intro:
    "Please read this disclaimer carefully before relying on any YourTruths evaluation, score, or verdict.",
  sections: [
    {
      heading: "1. How YourTruths evaluations are produced",
      paragraphs: [
        "YourTruths generates AI-assisted evaluations through its Pro Examiner evaluation system. For free AI categories (text, PDFs, images, physical appearance, and similar), AI analyzes what you submit and returns a structured opinion—typically including a 0–100 YourTruths score, strengths, weaknesses, and a focused written verdict.",
        "For music and video Hybrid reviews, a human reviewer first experiences the work and provides notes; YourTruths AI then rewrites those notes into the same style of structured evaluation.",
      ],
    },
    {
      heading: "2. Opinions and analysis — not objective truth",
      paragraphs: [
        "Evaluations are opinions and analytical outputs. They are not statements of objective truth, certification, appraisal, lab measurement, or professional endorsement.",
      ],
    },
    {
      heading: "3. AI can be wrong",
      paragraphs: [
        "AI systems can be incorrect, incomplete, inconsistent, or biased. They may miss context, misunderstand creative intent, or produce uneven results across languages, genres, or formats.",
      ],
    },
    {
      heading: "4. Scores are not professional advice",
      paragraphs: [
        "YourTruths scores (0–100 ranking bands) and written verdicts should not be treated as legal, financial, medical, therapeutic, investment, academic grading, career, or other professional advice.",
        "Do not use an evaluation as the sole basis for high-stakes decisions.",
      ],
    },
    {
      heading: "5. Your responsibility",
      paragraphs: [
        "You remain solely responsible for decisions you make based on any evaluation, including creative, business, publishing, release, hiring, or personal choices.",
      ],
    },
    {
      heading: "6. Human reviews are individual perspectives",
      paragraphs: [
        "When a human reviewer participates, their reaction is an individual perspective—not a universal audience consensus, market forecast, or guarantee of reception.",
        "Different reviewers may disagree. Priority or “best reviewer” labeling, if offered, does not convert an opinion into an objective standard.",
      ],
    },
    {
      heading: "7. No outcome guarantees",
      paragraphs: [
        "YourTruths does not guarantee artistic success, business results, virality, grades, employment outcomes, or any other result from using the Service or following an evaluation.",
        "YourTruths is designed to reduce cheerleading and provide an independent perspective—not to tell you only what you want to hear, and not to promise that an independent perspective is always correct.",
      ],
    },
  ],
};

export const CONTENT_POLICY: LegalDoc = {
  title: "User Content & Copyright Policy",
  slug: "content-policy",
  intro:
    "This Policy explains ownership of user content, the limited permissions you grant YourTruths, copyright rules, and how human reviewers may access music and video submissions.",
  sections: [
    {
      heading: "1. You retain ownership",
      paragraphs: [
        "You retain ownership of the original work you upload or submit to YourTruths, subject to third-party rights that already apply to that work.",
      ],
    },
    {
      heading: "2. Limited license to operate the Service",
      paragraphs: [
        "By submitting content, you grant YourTruths a worldwide, non-exclusive license to host, process, transmit, reproduce, adapt (for formatting or AI restructuring into an evaluation), display, and otherwise use the content only as reasonably necessary to provide the evaluation or Hybrid review you requested, to operate and secure the Service, and to comply with law.",
        "This license is not a transfer of ownership and is not a grant for YourTruths to sell or redistribute your work as a commercial content catalog unrelated to providing the Service.",
      ],
    },
    {
      heading: "3. Rights you must have",
      paragraphs: [
        "You represent that you have all rights, licenses, and permissions needed to submit the content and to authorize the processing described in these policies—including rights from collaborators, labels, clients, or licensors where required.",
      ],
    },
    {
      heading: "4. Copyright infringement prohibited",
      paragraphs: [
        "You may not upload content that infringes copyright or other intellectual property rights. We may remove or disable access to material we reasonably believe is infringing and may suspend accounts that repeatedly infringe.",
      ],
    },
    {
      heading: "5. Reporting copyright concerns",
      paragraphs: [
        `If you believe content processed or stored in connection with YourTruths infringes your copyright, email ${LEGAL_CONTACT_EMAIL} with:`,
      ],
      bullets: [
        "Your contact name and email",
        "Description of the copyrighted work",
        "Location, URL, or job or result identifier of the allegedly infringing material (if available)",
        "A statement that you have a good-faith belief the use is not authorized",
        "A statement that the information is accurate and, under penalty of perjury where applicable, that you are the owner or authorized to act",
        "Your physical or electronic signature (typing your full name can suffice for email)",
      ],
    },
    {
      heading: "6. Human reviewer access",
      paragraphs: [
        "For music and video Hybrid reviews, human reviewers access only the content necessary to perform the review (for example, the audio or video file and related context). Reviewers are expected to use that access solely for evaluation purposes.",
      ],
    },
    {
      heading: "7. Confidentiality",
      paragraphs: [
        "We treat user submissions as confidential operational data of the Service and do not sell user uploads as a content library.",
        "Confidentiality is not absolute: content is processed by systems and providers as described in the Privacy Policy; reviewers see what they need to review; and we may disclose information if required by law or to protect rights, safety, and security.",
        "If a package is labeled private (for example, Hybrid PRO private use), we take reasonable steps consistent with that offering to avoid featuring your opinion in public or shared feeds, subject to technical limits and legal requirements.",
      ],
    },
    {
      heading: "8. Sharing and public features",
      paragraphs: [
        "Where the Service offers share controls at Submit or displays examples, follow the in-product options. Do not submit material you are unwilling to have processed under the Privacy Policy and these Terms.",
      ],
    },
    {
      heading: "9. Contact",
      paragraphs: [
        `Content and copyright questions: ${LEGAL_CONTACT_EMAIL}.`,
      ],
    },
  ],
};

export const CONTACT_PAGE = {
  title: "Contact",
  intro:
    "This is the current public contact address for YourTruths support, privacy requests, refund questions, copyright notices, and legal inquiries. A dedicated company email may be added later; until then, use the address below.",
  email: LEGAL_CONTACT_EMAIL,
  notes: [
    "Please include enough detail for us to help (account email if any, page URL, job or result ID if relevant, and a clear description).",
    "For privacy, ARCO, or U.S. privacy requests, state the type of request and the email tied to your use of the Service.",
    "For copyright notices, include the information listed in the User Content & Copyright Policy.",
    "For refund requests, include purchase date, amount, pack type, and what went wrong.",
    "We aim to respond in a reasonable time, but response times may vary.",
  ],
} as const;

export function getLegalDoc(slug: string): LegalDoc | null {
  const docs = [TERMS_OF_SERVICE, PRIVACY_POLICY, REFUND_POLICY, AI_DISCLAIMER, CONTENT_POLICY];
  return docs.find((doc) => doc.slug === slug) ?? null;
}
