export const STRENGTH_TAGS = [
  "Strong hook",
  "Clear idea",
  "Good taste",
  "Tight mix",
  "Clean layout",
  "Holds together",
  "Sharp image",
  "Real voice",
  "Good pacing",
  "Strong ending",
  "Bold choice",
  "Easy to read",
  "Warm sound",
  "Simple and clear",
  "High craft",
  "Good contrast",
  "Sells the idea",
  "Memorable",
  "Honest",
  "Tight writing",
  "Strong type",
  "Good energy",
  "Clear hierarchy",
  "Finished",
  "Distinct",
  "Hits the brief",
  "Emotional",
  "Balanced",
  "Confident",
  "Nothing extra",
] as const;

export const WEAKNESS_TAGS = [
  "Weak as a poster",
  "Idea not there",
  "No hook",
  "Flat mix",
  "Lost in the middle",
  "Looks unfinished",
  "Hard to read",
  "No point of view",
  "Too safe",
  "Timing is off",
  "Cheap production",
  "Confusing layout",
  "Weak ending",
  "No contrast",
  "Overworked",
  "Underbaked",
  "Generic",
  "Too long",
  "Too quiet",
  "Off-brief",
  "No emotion",
  "Cluttered",
  "Thin sound",
  "Dead composition",
  "Weak type",
  "No sell",
  "Falls apart",
  "Uneven",
  "Forgettable",
  "Tries too hard",
] as const;
